# Generated by Django 4.2.1 on 2023-05-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.ImageField(default='/', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
